platform :ios, '5.1.1'

pod 'HPGrowingTextView'
pod 'SDWebImage'
pod 'NavigationMenu', :podspec => './PodsSpecs/NavigationMenu.podspec'
pod 'DAKeyboardControl'
pod 'UIBubbleTableView'

target :FirerageKitTests do
    pod "GHUnit", "0.5.8"
end

target :FirerageKitTests do
    pod "OCMock"
end