platform :ios, '5.1.1'

pod 'SDWebImage'
pod 'DAKeyboardControl'
pod 'UIBubbleTableView'
pod 'AKSegmentedControl'
pod 'UIColor+MLPFlatColors', '~> 1.0'
pod 'NavigationMenu', :podspec => './PodsSpecs/NavigationMenu.podspec'
pod 'GCPlaceholderTextView', :podspec => './PodsSpecs/GCPlaceholderTextView.podspec'
pod 'BButton', :podspec => './PodsSpecs/BButton.podspec'

target :FirerageKitTests do
    pod "GHUnit", "0.5.8"
end

target :FirerageKitTests do
    pod "OCMock"
end